from ShasaBot import DEV_USERS, FAFNIRS, LUINORS, REDLIONS, SPRYZONS, telethn

IMMUNE_USERS = REDLIONS + LUINORS + SPRYZONS + FAFNIRS + DEV_USERS

IMMUNE_USERS = (
    list(REDLIONS) + list(LUINORS) + list(SPRYZONS) + list(FAFNIRS) + list(DEV_USERS)
)
